version: '3.7'

networks:
  overlay-net:
    external: true      
    driver: overlay

services:

  prod:
    image: iudx/di-depl:latest
    environment:
      - DI_URL=https://di.iudx.org.in
      - LOG_LEVEL=INFO
      - DI_JAVA_OPTS=-Xmx4096m
    volumes:
      - ./configs/config-depl.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    depends_on:
      - "zookeeper"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9000:9000"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$DI_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"

  dev:
    image: iudx/di-dev:latest
    environment:
      - DI_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - RS_JAVA_OPTS=-Xmx1024m
    volumes:
      - ./configs/config-dev.json:/usr/share/app/configs/config.json
      - ./configs/keystore.jks:/usr/share/app/configs/keystore.jks
    ports:
      - "8080:8080"
      - "8443:8443"
    restart: on-failure
    networks: 
      - overlay-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "exec java $$RS_JAVA_OPTS  -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.Log4j2LogDelegateFactory -jar ./fatjar.jar  --host $$(hostname) -c configs/config.json"


  zookeeper:
    image: zookeeper:latest
    expose: 
      - "2181"
    networks:
      - overlay-net
